#!/bin/bash
set -e

cd $(dirname $0)/..

VERSION=${VERSION:?"VERSION not set"}
ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

rm -rf ./dist/artifacts
mkdir -p ./dist/artifacts/

pwd
cd /tmp/iperf && pwd && tar cvfz iperf-v${VERSION}${SUFFIX}.tar.gz usr && ls -l && cd -
mv /tmp/iperf/iperf-v${VERSION}${SUFFIX}.tar.gz ./dist/artifacts/
ls -lah ./dist/artifacts/iperf-v${VERSION}${SUFFIX}.tar.gz
